import { Item } from "./types";

export const data: Item[] = [
  {
    label: "Spaghetti Carbonara",
    value: "spaghetti_carbonara",
    category: "Pasta",
    description: "Classic Italian pasta with creamy egg sauce and pancetta.",
  },
  {
    label: "Margherita Pizza",
    value: "margherita_pizza",
    category: "Pizza",
    description:
      "Traditional pizza with fresh tomatoes, mozzarella, and basil.",
  },
  {
    label: "Caesar Salad",
    value: "caesar_salad",
    category: "Salad",
    description:
      "Crisp romaine lettuce with Caesar dressing, croutons, and parmesan.",
  },
  {
    label: "Grilled Chicken Sandwich",
    value: "grilled_chicken_sandwich",
    category: "Sandwich",
    description: "Juicy grilled chicken breast with lettuce, tomato, and mayo.",
  },
  {
    label: "Beef Tacos",
    value: "beef_tacos",
    category: "Mexican",
    description:
      "Soft tortillas filled with seasoned beef, lettuce, and cheese.",
  },
  {
    label: "Vegetable Stir Fry",
    value: "vegetable_stir_fry",
    category: "Asian",
    description: "Mixed vegetables sautéed in a savory soy sauce.",
  },
  {
    label: "Cheeseburger",
    value: "cheeseburger",
    category: "Burger",
    description: "Grilled beef patty with melted cheese, lettuce, and tomato.",
  },
  {
    label: "Chicken Alfredo",
    value: "chicken_alfredo",
    category: "Pasta",
    description: "Creamy Alfredo sauce with grilled chicken over fettuccine.",
  },
  {
    label: "Pepperoni Pizza",
    value: "pepperoni_pizza",
    category: "Pizza",
    description: "Pizza topped with spicy pepperoni and mozzarella cheese.",
  },
  {
    label: "Greek Salad",
    value: "greek_salad",
    category: "Salad",
    description:
      "Fresh salad with cucumbers, tomatoes, olives, and feta cheese.",
  },
  {
    label: "Turkey Club Sandwich",
    value: "turkey_club_sandwich",
    category: "Sandwich",
    description:
      "Triple-decker sandwich with turkey, bacon, lettuce, and tomato.",
  },
  {
    label: "Chicken Quesadilla",
    value: "chicken_quesadilla",
    category: "Mexican",
    description: "Grilled tortilla filled with chicken, cheese, and peppers.",
  },
  {
    label: "Beef and Broccoli",
    value: "beef_and_broccoli",
    category: "Asian",
    description: "Tender beef and broccoli florets in a savory sauce.",
  },
  {
    label: "Veggie Burger",
    value: "veggie_burger",
    category: "Burger",
    description: "Plant-based patty with lettuce, tomato, and avocado.",
  },
  {
    label: "Shrimp Scampi",
    value: "shrimp_scampi",
    category: "Pasta",
    description: "Shrimp sautéed in garlic butter sauce over linguine.",
  },
  {
    label: "BBQ Chicken Pizza",
    value: "bbq_chicken_pizza",
    category: "Pizza",
    description: "Pizza topped with BBQ chicken, red onions, and cilantro.",
  },
  {
    label: "Caprese Salad",
    value: "caprese_salad",
    category: "Salad",
    description:
      "Fresh mozzarella, tomatoes, and basil drizzled with balsamic.",
  },
  {
    label: "BLT Sandwich",
    value: "blt_sandwich",
    category: "Sandwich",
    description: "Crispy bacon, lettuce, and tomato on toasted bread.",
  },
  {
    label: "Fish Tacos",
    value: "fish_tacos",
    category: "Mexican",
    description:
      "Grilled fish with cabbage slaw and lime crema in soft tortillas.",
  },
  {
    label: "Chicken Teriyaki",
    value: "chicken_teriyaki",
    category: "Asian",
    description: "Grilled chicken glazed with teriyaki sauce served with rice.",
  },
  {
    label: "Mushroom Burger",
    value: "mushroom_burger",
    category: "Burger",
    description: "Beef patty topped with sautéed mushrooms and Swiss cheese.",
  },
  {
    label: "Penne Arrabbiata",
    value: "penne_arrabbiata",
    category: "Pasta",
    description: "Spicy tomato sauce over penne pasta.",
  },
  {
    label: "Hawaiian Pizza",
    value: "hawaiian_pizza",
    category: "Pizza",
    description: "Pizza topped with ham, pineapple, and mozzarella cheese.",
  },
  {
    label: "Cobb Salad",
    value: "cobb_salad",
    category: "Salad",
    description: "Mixed greens with chicken, bacon, avocado, and blue cheese.",
  },
  {
    label: "Ham and Cheese Sandwich",
    value: "ham_and_cheese_sandwich",
    category: "Sandwich",
    description: "Classic sandwich with ham, cheese, and mustard.",
  },
  {
    label: "Chicken Enchiladas",
    value: "chicken_enchiladas",
    category: "Mexican",
    description:
      "Corn tortillas filled with chicken and topped with enchilada sauce.",
  },
  {
    label: "Sweet and Sour Chicken",
    value: "sweet_and_sour_chicken",
    category: "Asian",
    description: "Chicken pieces in a tangy sweet and sour sauce.",
  },
  {
    label: "Bacon Cheeseburger",
    value: "bacon_cheeseburger",
    category: "Burger",
    description: "Beef patty with bacon, cheese, lettuce, and tomato.",
  },
  {
    label: "Lasagna",
    value: "lasagna",
    category: "Pasta",
    description: "Layers of pasta, meat sauce, and cheese baked to perfection.",
  },
  {
    label: "Four Cheese Pizza",
    value: "four_cheese_pizza",
    category: "Pizza",
    description:
      "Pizza topped with a blend of mozzarella, cheddar, parmesan, and blue cheese.",
  },
  {
    label: "Spinach Salad",
    value: "spinach_salad",
    category: "Salad",
    description:
      "Fresh spinach with strawberries, almonds, and poppy seed dressing.",
  },
  {
    label: "Roast Beef Sandwich",
    value: "roast_beef_sandwich",
    category: "Sandwich",
    description: "Thinly sliced roast beef with horseradish sauce on a roll.",
  },
  {
    label: "Carnitas Tacos",
    value: "carnitas_tacos",
    category: "Mexican",
    description: "Slow-cooked pork with onions and cilantro in soft tortillas.",
  },
  {
    label: "General Tso's Chicken",
    value: "general_tsos_chicken",
    category: "Asian",
    description: "Crispy chicken in a sweet and spicy sauce.",
  },
  {
    label: "Turkey Burger",
    value: "turkey_burger",
    category: "Burger",
    description: "Lean turkey patty with lettuce, tomato, and avocado.",
  },
  {
    label: "Fettuccine Alfredo",
    value: "fettuccine_alfredo",
    category: "Pasta",
    description: "Creamy Alfredo sauce over fettuccine pasta.",
  },
  {
    label: "Meat Lovers Pizza",
    value: "meat_lovers_pizza",
    category: "Pizza",
    description: "Pizza topped with pepperoni, sausage, bacon, and ham.",
  },
  {
    label: "Waldorf Salad",
    value: "waldorf_salad",
    category: "Salad",
    description:
      "Salad with apples, walnuts, celery, and grapes in a creamy dressing.",
  },
  {
    label: "Tuna Salad Sandwich",
    value: "tuna_salad_sandwich",
    category: "Sandwich",
    description: "Tuna salad with lettuce and tomato on whole grain bread.",
  },
  {
    label: "Chicken Fajitas",
    value: "chicken_fajitas",
    category: "Mexican",
    description:
      "Sizzling chicken with peppers and onions served with tortillas.",
  },
  {
    label: "Orange Chicken",
    value: "orange_chicken",
    category: "Asian",
    description: "Crispy chicken in a tangy orange sauce.",
  },
  {
    label: "Black Bean Burger",
    value: "black_bean_burger",
    category: "Burger",
    description: "Vegetarian burger made with black beans and spices.",
  },
  {
    label: "Pasta Primavera",
    value: "pasta_primavera",
    category: "Pasta",
    description: "Pasta with fresh vegetables in a light garlic sauce.",
  },
  {
    label: "Buffalo Chicken Pizza",
    value: "buffalo_chicken_pizza",
    category: "Pizza",
    description: "Pizza topped with spicy buffalo chicken and blue cheese.",
  },
  {
    label: "Quinoa Salad",
    value: "quinoa_salad",
    category: "Salad",
    description:
      "Healthy salad with quinoa, vegetables, and lemon vinaigrette.",
  },
  {
    label: "Egg Salad Sandwich",
    value: "egg_salad_sandwich",
    category: "Sandwich",
    description: "Egg salad with lettuce on whole grain bread.",
  },
  {
    label: "Steak Tacos",
    value: "steak_tacos",
    category: "Mexican",
    description: "Grilled steak with onions and cilantro in soft tortillas.",
  },
  {
    label: "Kung Pao Chicken",
    value: "kung_pao_chicken",
    category: "Asian",
    description: "Spicy stir-fried chicken with peanuts and vegetables.",
  },
  {
    label: "Salmon Burger",
    value: "salmon_burger",
    category: "Burger",
    description: "Grilled salmon patty with lettuce, tomato, and dill sauce.",
  },
  {
    label: "Ravioli",
    value: "ravioli",
    category: "Pasta",
    description:
      "Pasta pockets filled with cheese and served with marinara sauce.",
  },
  {
    label: "Veggie Pizza",
    value: "veggie_pizza",
    category: "Pizza",
    description: "Pizza topped with a variety of fresh vegetables.",
  },
  {
    label: "Chicken Caesar Salad",
    value: "chicken_caesar_salad",
    category: "Salad",
    description: "Caesar salad topped with grilled chicken breast.",
  },
  {
    label: "Pulled Pork Sandwich",
    value: "pulled_pork_sandwich",
    category: "Sandwich",
    description: "Slow-cooked pulled pork with BBQ sauce on a bun.",
  },
  {
    label: "Shrimp Tacos",
    value: "shrimp_tacos",
    category: "Mexican",
    description:
      "Grilled shrimp with cabbage slaw and lime crema in soft tortillas.",
  },
  {
    label: "Sesame Chicken",
    value: "sesame_chicken",
    category: "Asian",
    description: "Crispy chicken in a sweet sesame sauce.",
  },
  {
    label: "Portobello Burger",
    value: "portobello_burger",
    category: "Burger",
    description: "Grilled portobello mushroom with lettuce, tomato, and pesto.",
  },
  {
    label: "Spaghetti Bolognese",
    value: "spaghetti_bolognese",
    category: "Pasta",
    description: "Spaghetti with a rich meat sauce.",
  },
  {
    label: "Prosciutto Pizza",
    value: "prosciutto_pizza",
    category: "Pizza",
    description: "Pizza topped with prosciutto, arugula, and mozzarella.",
  },
  {
    label: "Arugula Salad",
    value: "arugula_salad",
    category: "Salad",
    description:
      "Fresh arugula with cherry tomatoes, parmesan, and lemon vinaigrette.",
  },
  {
    label: "Chicken Salad Sandwich",
    value: "chicken_salad_sandwich",
    category: "Sandwich",
    description: "Chicken salad with lettuce and tomato on whole grain bread.",
  },
  {
    label: "Beef Burritos",
    value: "beef_burritos",
    category: "Mexican",
    description: "Flour tortillas filled with seasoned beef, rice, and beans.",
  },
  {
    label: "Mongolian Beef",
    value: "mongolian_beef",
    category: "Asian",
    description: "Tender beef stir-fried with green onions in a savory sauce.",
  },
  {
    label: "Lamb Burger",
    value: "lamb_burger",
    category: "Burger",
    description: "Juicy lamb patty with lettuce, tomato, and tzatziki sauce.",
  },
  {
    label: "Pesto Pasta",
    value: "pesto_pasta",
    category: "Pasta",
    description: "Pasta tossed in a fresh basil pesto sauce.",
  },
  {
    label: "Sausage Pizza",
    value: "sausage_pizza",
    category: "Pizza",
    description: "Pizza topped with Italian sausage and mozzarella cheese.",
  },
  {
    label: "Kale Salad",
    value: "kale_salad",
    category: "Salad",
    description: "Fresh kale with cranberries, almonds, and lemon vinaigrette.",
  },
  {
    label: "Reuben Sandwich",
    value: "reuben_sandwich",
    category: "Sandwich",
    description: "Corned beef, sauerkraut, and Swiss cheese on rye bread.",
  },
  {
    label: "Chicken Tostadas",
    value: "chicken_tostadas",
    category: "Mexican",
    description: "Crispy tortillas topped with chicken, beans, and avocado.",
  },
  {
    label: "Lemon Chicken",
    value: "lemon_chicken",
    category: "Asian",
    description: "Crispy chicken in a tangy lemon sauce.",
  },
  {
    label: "Falafel Burger",
    value: "falafel_burger",
    category: "Burger",
    description: "Vegetarian burger made with spiced chickpea patties.",
  },
  {
    label: "Tortellini",
    value: "tortellini",
    category: "Pasta",
    description: "Cheese-filled pasta served with marinara sauce.",
  },
  {
    label: "Marinara Pizza",
    value: "marinara_pizza",
    category: "Pizza",
    description: "Pizza topped with marinara sauce, garlic, and oregano.",
  },
  {
    label: "Mixed Green Salad",
    value: "mixed_green_salad",
    category: "Salad",
    description:
      "Fresh mixed greens with tomatoes, cucumbers, and balsamic vinaigrette.",
  },
  {
    label: "Philly Cheesesteak",
    value: "philly_cheesesteak",
    category: "Sandwich",
    description:
      "Thinly sliced steak with melted cheese and onions on a hoagie roll.",
  },
  {
    label: "Pork Tacos",
    value: "pork_tacos",
    category: "Mexican",
    description:
      "Soft tortillas filled with seasoned pork, onions, and cilantro.",
  },
  {
    label: "Teriyaki Salmon",
    value: "teriyaki_salmon",
    category: "Asian",
    description: "Grilled salmon glazed with teriyaki sauce served with rice.",
  },
  {
    label: "BBQ Burger",
    value: "bbq_burger",
    category: "Burger",
    description: "Beef patty with BBQ sauce, cheddar cheese, and onion rings.",
  },
  {
    label: "Linguine with Clams",
    value: "linguine_with_clams",
    category: "Pasta",
    description: "Linguine pasta with clams in a white wine garlic sauce.",
  },
  {
    label: "White Pizza",
    value: "white_pizza",
    category: "Pizza",
    description: "Pizza topped with ricotta, mozzarella, and garlic.",
  },
  {
    label: "Beet Salad",
    value: "beet_salad",
    category: "Salad",
    description: "Roasted beets with goat cheese, walnuts, and arugula.",
  },
  {
    label: "Grilled Cheese Sandwich",
    value: "grilled_cheese_sandwich",
    category: "Sandwich",
    description: "Melted cheese between two slices of toasted bread.",
  },
  {
    label: "Chicken Burritos",
    value: "chicken_burritos",
    category: "Mexican",
    description:
      "Flour tortillas filled with seasoned chicken, rice, and beans.",
  },
  {
    label: "Szechuan Beef",
    value: "szechuan_beef",
    category: "Asian",
    description: "Spicy stir-fried beef with Szechuan peppers and vegetables.",
  },
  {
    label: "Bison Burger",
    value: "bison_burger",
    category: "Burger",
    description: "Lean bison patty with lettuce, tomato, and onion.",
  },
  {
    label: "Eggplant Parmesan",
    value: "eggplant_parmesan",
    category: "Pasta",
    description:
      "Breaded eggplant slices baked with marinara sauce and cheese.",
  },
  {
    label: "BBQ Ribs",
    value: "bbq_ribs",
    category: "BBQ",
    description: "Slow-cooked ribs with a smoky BBQ sauce.",
  },
  {
    label: "Lobster Roll",
    value: "lobster_roll",
    category: "Seafood",
    description: "Fresh lobster meat in a buttered roll.",
  },
  {
    label: "Clam Chowder",
    value: "clam_chowder",
    category: "Soup",
    description: "Creamy soup with clams, potatoes, and bacon.",
  },
  {
    label: "Stuffed Peppers",
    value: "stuffed_peppers",
    category: "Vegetarian",
    description: "Bell peppers stuffed with rice, vegetables, and cheese.",
  },
  {
    label: "Chicken Parmesan",
    value: "chicken_parmesan",
    category: "Pasta",
    description: "Breaded chicken breast topped with marinara and mozzarella.",
  },
  {
    label: "Beef Stroganoff",
    value: "beef_stroganoff",
    category: "Pasta",
    description: "Tender beef in a creamy mushroom sauce over egg noodles.",
  },
  {
    label: "Seafood Paella",
    value: "seafood_paella",
    category: "Seafood",
    description: "Spanish rice dish with shrimp, mussels, and saffron.",
  },
  {
    label: "Minestrone Soup",
    value: "minestrone_soup",
    category: "Soup",
    description: "Hearty Italian soup with vegetables and pasta.",
  },
  {
    label: "Chicken Pot Pie",
    value: "chicken_pot_pie",
    category: "Pie",
    description: "Creamy chicken and vegetables in a flaky crust.",
  },
  {
    label: "Vegetable Curry",
    value: "vegetable_curry",
    category: "Vegetarian",
    description: "Mixed vegetables in a spicy curry sauce.",
  },
  {
    label: "Beef Wellington",
    value: "beef_wellington",
    category: "Beef",
    description:
      "Beef tenderloin wrapped in puff pastry with mushroom duxelles.",
  },
  {
    label: "Shrimp Cocktail",
    value: "shrimp_cocktail",
    category: "Appetizer",
    description: "Chilled shrimp served with cocktail sauce.",
  },
  {
    label: "French Onion Soup",
    value: "french_onion_soup",
    category: "Soup",
    description: "Rich beef broth with caramelized onions and melted cheese.",
  },
  {
    label: "Chicken Marsala",
    value: "chicken_marsala",
    category: "Pasta",
    description: "Chicken breast in a Marsala wine and mushroom sauce.",
  },
  {
    label: "Lamb Chops",
    value: "lamb_chops",
    category: "Lamb",
    description: "Grilled lamb chops with rosemary and garlic.",
  },
  {
    label: "Crab Cakes",
    value: "crab_cakes",
    category: "Seafood",
    description: "Pan-fried crab cakes with a tangy remoulade sauce.",
  },
  {
    label: "Tomato Basil Soup",
    value: "tomato_basil_soup",
    category: "Soup",
    description: "Creamy tomato soup with fresh basil.",
  },
  {
    label: "Chicken Piccata",
    value: "chicken_piccata",
    category: "Pasta",
    description: "Chicken breast in a lemon caper sauce.",
  },
  {
    label: "Duck Confit",
    value: "duck_confit",
    category: "Duck",
    description: "Slow-cooked duck leg with crispy skin.",
  },
  {
    label: "Oysters Rockefeller",
    value: "oysters_rockefeller",
    category: "Appetizer",
    description: "Baked oysters with spinach and hollandaise sauce.",
  },
  {
    label: "Gazpacho",
    value: "gazpacho",
    category: "Soup",
    description: "Chilled tomato soup with cucumbers and peppers.",
  },
  {
    label: "Veal Scallopini",
    value: "veal_scallopini",
    category: "Veal",
    description: "Thinly sliced veal in a lemon butter sauce.",
  },
  {
    label: "Salmon Tartare",
    value: "salmon_tartare",
    category: "Appetizer",
    description: "Raw salmon mixed with herbs and lemon.",
  },
  {
    label: "Butternut Squash Soup",
    value: "butternut_squash_soup",
    category: "Soup",
    description: "Creamy soup made with roasted butternut squash.",
  },
  {
    label: "Eggs Benedict",
    value: "eggs_benedict",
    category: "Breakfast",
    description: "Poached eggs on English muffins with hollandaise sauce.",
  },
  {
    label: "Rack of Lamb",
    value: "rack_of_lamb",
    category: "Lamb",
    description: "Herb-crusted rack of lamb with mint sauce.",
  },
  {
    label: "Lobster Bisque",
    value: "lobster_bisque",
    category: "Soup",
    description: "Rich and creamy lobster soup.",
  },
  {
    label: "Peking Duck",
    value: "peking_duck",
    category: "Duck",
    description: "Crispy duck served with pancakes and hoisin sauce.",
  },
  {
    label: "Beef Carpaccio",
    value: "beef_carpaccio",
    category: "Appetizer",
    description: "Thinly sliced raw beef with olive oil and parmesan.",
  },
  {
    label: "Miso Soup",
    value: "miso_soup",
    category: "Soup",
    description: "Traditional Japanese soup with tofu and seaweed.",
  },
  {
    label: "Chicken Cordon Bleu",
    value: "chicken_cordon_bleu",
    category: "Pasta",
    description:
      "Chicken breast stuffed with ham and cheese, breaded and fried.",
  },
  {
    label: "Lamb Shank",
    value: "lamb_shank",
    category: "Lamb",
    description: "Braised lamb shank with red wine sauce.",
  },
  {
    label: "Shrimp Tempura",
    value: "shrimp_tempura",
    category: "Appetizer",
    description: "Lightly battered and fried shrimp.",
  },
  {
    label: "Pumpkin Soup",
    value: "pumpkin_soup",
    category: "Soup",
    description: "Creamy soup made with roasted pumpkin.",
  },
  {
    label: "Chicken Kiev",
    value: "chicken_kiev",
    category: "Pasta",
    description:
      "Chicken breast stuffed with garlic butter, breaded and fried.",
  },
  {
    label: "Venison Stew",
    value: "venison_stew",
    category: "Stew",
    description: "Hearty stew made with tender venison.",
  },
  {
    label: "Calamari",
    value: "calamari",
    category: "Appetizer",
    description: "Fried squid rings served with marinara sauce.",
  },
  {
    label: "Broccoli Cheddar Soup",
    value: "broccoli_cheddar_soup",
    category: "Soup",
    description: "Creamy soup with broccoli and cheddar cheese.",
  },
  {
    label: "Chicken Tikka Masala",
    value: "chicken_tikka_masala",
    category: "Indian",
    description: "Chicken in a creamy tomato curry sauce.",
  },
  {
    label: "Lamb Rogan Josh",
    value: "lamb_rogan_josh",
    category: "Indian",
    description: "Spicy lamb curry with yogurt and spices.",
  },
  {
    label: "Bruschetta",
    value: "bruschetta",
    category: "Appetizer",
    description: "Grilled bread topped with tomatoes, basil, and olive oil.",
  },
  {
    label: "Potato Leek Soup",
    value: "potato_leek_soup",
    category: "Soup",
    description: "Creamy soup made with potatoes and leeks.",
  },
  {
    label: "Chicken Satay",
    value: "chicken_satay",
    category: "Appetizer",
    description: "Grilled chicken skewers with peanut sauce.",
  },
  {
    label: "Lamb Vindaloo",
    value: "lamb_vindaloo",
    category: "Indian",
    description: "Spicy lamb curry with vinegar and potatoes.",
  },
  {
    label: "Caprese Skewers",
    value: "caprese_skewers",
    category: "Appetizer",
    description: "Skewers with mozzarella, tomatoes, and basil.",
  },
  {
    label: "Corn Chowder",
    value: "corn_chowder",
    category: "Soup",
    description: "Creamy soup with corn, potatoes, and bacon.",
  },
  {
    label: "Chicken Shawarma",
    value: "chicken_shawarma",
    category: "Middle Eastern",
    description: "Marinated chicken served with pita and garlic sauce.",
  },
  {
    label: "Lamb Kebab",
    value: "lamb_kebab",
    category: "Middle Eastern",
    description: "Grilled lamb skewers with spices.",
  },
  {
    label: "Stuffed Mushrooms",
    value: "stuffed_mushrooms",
    category: "Appetizer",
    description: "Mushrooms stuffed with cheese and herbs.",
  },
  {
    label: "Split Pea Soup",
    value: "split_pea_soup",
    category: "Soup",
    description: "Hearty soup made with split peas and ham.",
  },
  {
    label: "Chicken Gyro",
    value: "chicken_gyro",
    category: "Greek",
    description: "Grilled chicken in pita with tzatziki sauce.",
  },
  {
    label: "Lamb Moussaka",
    value: "lamb_moussaka",
    category: "Greek",
    description: "Layered casserole with lamb, eggplant, and béchamel sauce.",
  },
  {
    label: "Deviled Eggs",
    value: "deviled_eggs",
    category: "Appetizer",
    description: "Hard-boiled eggs filled with a seasoned yolk mixture.",
  },
  {
    label: "Lentil Soup",
    value: "lentil_soup",
    category: "Soup",
    description: "Hearty soup made with lentils and vegetables.",
  },
  {
    label: "Chicken Souvlaki",
    value: "chicken_souvlaki",
    category: "Greek",
    description: "Grilled chicken skewers with lemon and oregano.",
  },
  {
    label: "Lamb Gyro",
    value: "lamb_gyro",
    category: "Greek",
    description: "Grilled lamb in pita with tzatziki sauce.",
  },
  {
    label: "Baba Ganoush",
    value: "baba_ganoush",
    category: "Appetizer",
    description: "Smoky eggplant dip with tahini and garlic.",
  },
  {
    label: "Mulligatawny Soup",
    value: "mulligatawny_soup",
    category: "Soup",
    description: "Spicy Indian soup with chicken and rice.",
  },
  {
    label: "Chicken Kebab",
    value: "chicken_kebab",
    category: "Middle Eastern",
    description: "Grilled chicken skewers with spices.",
  },
  {
    label: "Lamb Shawarma",
    value: "lamb_shawarma",
    category: "Middle Eastern",
    description: "Marinated lamb served with pita and garlic sauce.",
  },
  {
    label: "Spinach Artichoke Dip",
    value: "spinach_artichoke_dip",
    category: "Appetizer",
    description: "Creamy dip made with spinach and artichokes.",
  },
  {
    label: "Tom Yum Soup",
    value: "tom_yum_soup",
    category: "Soup",
    description: "Spicy Thai soup with shrimp and mushrooms.",
  },
  {
    label: "Chicken Korma",
    value: "chicken_korma",
    category: "Indian",
    description: "Mild chicken curry with yogurt and almonds.",
  },
  {
    label: "Lamb Biryani",
    value: "lamb_biryani",
    category: "Indian",
    description: "Spiced rice dish with lamb and vegetables.",
  },
  {
    label: "Crab Rangoon",
    value: "crab_rangoon",
    category: "Appetizer",
    description: "Fried wontons filled with crab and cream cheese.",
  },
  {
    label: "Mushroom Soup",
    value: "mushroom_soup",
    category: "Soup",
    description: "Creamy soup made with mushrooms and herbs.",
  },
  {
    label: "Chicken Tandoori",
    value: "chicken_tandoori",
    category: "Indian",
    description: "Marinated chicken cooked in a tandoor oven.",
  },
  {
    label: "Lamb Kofta",
    value: "lamb_kofta",
    category: "Middle Eastern",
    description: "Spiced lamb meatballs with herbs.",
  },
  {
    label: "Stuffed Grape Leaves",
    value: "stuffed_grape_leaves",
    category: "Appetizer",
    description: "Grape leaves stuffed with rice and herbs.",
  },
  {
    label: "Miso Ramen",
    value: "miso_ramen",
    category: "Soup",
    description: "Japanese noodle soup with miso broth and vegetables.",
  },
  {
    label: "Chicken Biryani",
    value: "chicken_biryani",
    category: "Indian",
    description: "Spiced rice dish with chicken and vegetables.",
  },
  {
    label: "Lamb Tagine",
    value: "lamb_tagine",
    category: "Moroccan",
    description: "Slow-cooked lamb stew with spices and dried fruits.",
  },
  {
    label: "Falafel",
    value: "falafel",
    category: "Appetizer",
    description: "Fried chickpea balls served with tahini sauce.",
  },
  {
    label: "Pho",
    value: "pho",
    category: "Soup",
    description: "Vietnamese noodle soup with beef and herbs.",
  },
  {
    label: "Chicken Vindaloo",
    value: "chicken_vindaloo",
    category: "Indian",
    description: "Spicy chicken curry with vinegar and potatoes.",
  },
  {
    label: "Lamb Curry",
    value: "lamb_curry",
    category: "Indian",
    description: "Spiced lamb curry with tomatoes and onions.",
  },
  {
    label: "Hummus",
    value: "hummus",
    category: "Appetizer",
    description: "Creamy chickpea dip with olive oil and garlic.",
  },
  {
    label: "Hot and Sour Soup",
    value: "hot_and_sour_soup",
    category: "Soup",
    description: "Spicy and tangy soup with tofu and mushrooms.",
  },
  {
    label: "Chicken Katsu",
    value: "chicken_katsu",
    category: "Japanese",
    description: "Breaded and fried chicken cutlet.",
  },
  {
    label: "Lamb Souvlaki",
    value: "lamb_souvlaki",
    category: "Greek",
    description: "Grilled lamb skewers with lemon and oregano.",
  },
  {
    label: "Spanakopita",
    value: "spanakopita",
    category: "Appetizer",
    description: "Greek spinach pie with feta cheese.",
  },
  {
    label: "French Lentil Soup",
    value: "french_lentil_soup",
    category: "Soup",
    description: "Hearty soup made with French lentils and vegetables.",
  },
  {
    label: "Chicken Biryani 2",
    value: "chicken_biryani_2",
    category: "Indian",
    description: "Spiced rice dish with chicken and vegetables.",
  },
  {
    label: "Lamb Tagine 2",
    value: "lamb_tagine_2",
    category: "Moroccan",
    description: "Slow-cooked lamb stew with spices and dried fruits.",
  },
  {
    label: "Falafel 2",
    value: "falafel_2",
    category: "Appetizer",
    description: "Fried chickpea balls served with tahini sauce.",
  },
  {
    label: "Pho 2",
    value: "pho_2",
    category: "Soup",
    description: "Vietnamese noodle soup with beef and herbs.",
  },
  {
    label: "Chicken Vindaloo 2",
    value: "chicken_vindaloo_2",
    category: "Indian",
    description: "Spicy chicken curry with vinegar and potatoes.",
  },
  {
    label: "Lamb Curry 2",
    value: "lamb_curry_2",
    category: "Indian",
    description: "Spiced lamb curry with tomatoes and onions.",
  },
  {
    label: "Hummus 2",
    value: "hummus_2",
    category: "Appetizer",
    description: "Creamy chickpea dip with olive oil and garlic.",
  },
  {
    label: "Hot and Sour Soup 2",
    value: "hot_and_sour_soup_2",
    category: "Soup",
    description: "Spicy and tangy soup with tofu and mushrooms.",
  },
  {
    label: "Chicken Katsu 2",
    value: "chicken_katsu_2",
    category: "Japanese",
    description: "Breaded and fried chicken cutlet.",
  },
  {
    label: "Lamb Souvlaki 2",
    value: "lamb_souvlaki_2",
    category: "Greek",
    description: "Grilled lamb skewers with lemon and oregano.",
  },
  {
    label: "Spanakopita 2",
    value: "spanakopita_2",
    category: "Appetizer",
    description: "Greek spinach pie with feta cheese.",
  },
  {
    label: "French Lentil Soup 2",
    value: "french_lentil_soup_2",
    category: "Soup",
    description: "Hearty soup made with French lentils and vegetables.",
  },
];
